# Generated by Django 3.2.9 on 2021-12-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='content',
        ),
    ]
