# Generated by Django 3.2.9 on 2021-12-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_description_service_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='content',
            new_name='description',
        ),
    ]
